name: news_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  retrofit: 3.0.1
  floor: 1.2.0
  flutter_bloc: any
  equatable: any
  get_it: any
  flutter_hooks: any
  lint: any
  ionicons: 0.1.2
  google_fonts: 2.2.0
  dio: 4.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  retrofit_generator:
  floor_generator:
  build_runner:
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

